#!/usr/bin/env bash
# ────────────────────────────────────────────
# install-tools.sh — Install tools from tool_hub registry
# Auto-generated by sync-hubs.sh — do not edit manually
# ────────────────────────────────────────────
set -euo pipefail

HUB_DIR="$(cd "$(dirname "$0")" && pwd)"
REGISTRY="$HUB_DIR/registry.json"

while IFS= read -r tool_id; do
  echo "Installing: $tool_id ..."
done < <(jq -r '.tools[].id' "$REGISTRY" 2>/dev/null)

echo "Done."
